### ISSUE TITLE
OpenSSL.SSL.Error: []

### ISSUE THREAD

**Issue by adamyala** [spohara79/estreamer#3]
I cloned the repo and installed dependancies. I'm using python 2.7. In `client.py` in the examples folder I set the following settings:
```
    with streamer.eStreamerConnection(
            host='https://my.firepower.url.com',
            port=8302,
            verify=basedir + 'estreamer.cer',
            cert_path=basedir + "firepower.crt",
            pkey_path=basedir + "firepower.pem",
            pkey_passphrase='passwordhere'
    ) as ec:
```
where `estreamer.cer` is a `.pkcs12` file that the admin gui gave me.

`firepower.crt` is the output from running:
```
openssl pkcs12 -in estreamer.cer -clcerts -nokeys -out firepower.crt
```
`firepower.pem` is the output from running:
```
openssl pkcs12 -in estreamer.cer -nocerts -out firepower.pem
```

When I run `python client.py` I get the below outut/error:
```
+--------------+-----------+---------------+---------------+
| name         | version   | author        | description   |
+--------------+-----------+---------------+---------------+
| PcapPlugin   | 0.1       | Sean O'Hara   | pcap writer   |
+--------------+-----------+---------------+---------------+

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/some/path/here/estreamer/examples/client.py", line 85, in <module>
    sys.exit(main())
  File "/some/path/here/estreamer/examples/client.py", line 54, in main
    pkey_passphrase='passwordhere'
  File "/another/path/here/lib/python2.7/site-packages/estreamer/streamer.py", line 57, in __enter__
    self.ctx.load_verify_locations(self.verify)
  File "/another/path/here/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/another/path/here/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []
```

Any idea what I'm doing wrong?

**Comment by spohara79** [comment]
you need to get the server certificate of the firepower device; you are trying to use the client cert bundle to verify the TLS connection.  you can do this with openssl:
`openssl s_client -connect <firepower_hostname>:<port> -showcerts

**Comment by adamyala** [comment]
Thank you. I changed it to:
```
    with streamer.eStreamerConnection(
            host='my.firepower.url.com',
            port=8302,
            verify=basedir + 'cert.from.my.server.crt',
            cert_path=basedir + "firepower.crt",
            pkey_path=basedir + "firepower.pem",
            pkey_passphrase='passwordhere'
    ) as ec:
```
For those brought here with the same issue, not I removed the protocol from my `host` as well.

And now I'm at the same error #2 is throwing. Thanks again.
